Update kubecost-single-account-permissions.yaml
kubecost/cloudformation pull request #16
Opened 2024-05-07 20:23 UTC by bstuder99

Changes requested by @chipzoller as part of https://github.com/kubecost/docs/issues/1029

2024-05-07 20:27 UTC, chipzoller approved these changes
Should also receive input from Solutions team.

2024-05-07 20:27 UTC, bstuder99 commented
Asking Sean right now

2024-05-07 21:07 UTC, srpomeroy requested changes
Line 106 needs to be updated to reflect the new parameter name.

We will also need to update `kubecost-masterpayer-account-permissions.yaml`

2024-05-07 21:38 UTC, bstuder99 commented
Good catch, both should be corrected now

2024-05-07 22:17 UTC, srpomeroy approved these changes
Two nits.

Should we update the name of the file from `kubecost-masterpayer-account-permissions.yaml` to `kubecost-management-account-permissions.yaml`? There are obviously repercussions for doing this elsewhere (docs).

2024-05-07 22:17 UTC, srpomeroy commented on kubecost-masterpayer-account-permissions.yaml
>      Description: The bucket where the CUR is sent from the “Setting up the CUR” step.
Nit. Do we want to update this to the same as the other CFT?
```suggestion
    Description: The bucket created to receive CUR data upon CUR creation.
```

2024-05-08 14:24 UTC, brstuder commented
I'm fine to update the file, as well as sweep for any other mentions of "masterpayer" in the docs which I believe AWS has retired.

2024-05-08 14:32 UTC, bstuder99 commented
I've renamed the file name and updated the link in the AWS doc, but there are other mentions across the AWS doc of masterPayerARN as a value. Maybe we can deal with all those in a separate PR?

2024-05-08 16:30 UTC, srpomeroy commented
> I've renamed the file name and updated the link in the AWS doc, but there are other mentions across the AWS doc of masterPayerARN as a value. Maybe we can deal with all those in a separate PR?

Yeah... Updating that property name is a larger lift as it's in the application itself.

2024-05-08 16:40 UTC, merged